In [1]:
import pandas as pd
import pandas_datareader as pdr

In [8]:
real_gdp = pdr.DataReader('GDPC1', data_source='fred', start='1947-01-01')
real_gdp['% Change'] = real_gdp['GDPC1'].pct_change()
real_gdp['% Change Annualised'] = real_gdp['% Change'] * 4

In [9]:
# CPI all
cpi_all = pdr.DataReader('CPIAUCSL', data_source='fred', start='1947-01-01')
cpi_all['% Change'] = cpi_all['CPIAUCSL'].pct_change()
cpi_all['Real GDP'] = real_gdp['% Change Annualised']
cpi_all

            CPIAUCSL  % Change  Real GDP
DATE
1947-01-01    21.480       NaN       NaN
1947-02-01    21.620  0.006518       NaN
1947-03-01    22.000  0.017576       NaN
1947-04-01    22.000  0.000000 -0.010668
1947-05-01    21.950 -0.002273       NaN
...              ...       ...       ...
2020-02-01   259.050  0.000889       NaN
2020-03-01   257.953 -0.004235       NaN
2020-04-01   255.902 -0.007951 -0.379789
2020-05-01   255.768 -0.000524       NaN
2020-06-01   257.214  0.005654       NaN

[882 rows x 3 columns]

In [11]:
# CPI x F&E
cpixfe = pdr.DataReader('CPILFESL', data_source='fred', start='1957-1-1')
cpixfe['% Change'] = cpixfe['CPILFESL'].pct_change()
cpixfe['Real GDP'] = real_gdp['% Change Annualised']
cpixfe

            CPILFESL  % Change  Real GDP
DATE
1957-01-01    28.500       NaN  0.025616
1957-02-01    28.600  0.003509       NaN
1957-03-01    28.700  0.003497       NaN
1957-04-01    28.800  0.003484 -0.008764
1957-05-01    28.800  0.000000       NaN
...              ...       ...       ...
2020-02-01   267.070  0.002229       NaN
2020-03-01   266.795 -0.001030       NaN
2020-04-01   265.601 -0.004475 -0.379789
2020-05-01   265.441 -0.000602       NaN
2020-06-01   266.065  0.002351       NaN

[762 rows x 3 columns]

In [13]:
# PPI all
ppi_all = pdr.DataReader('PPIACO', data_source='fred', start='1913-01-01')
ppi_all['% Change'] = ppi_all['PPIACO'].pct_change()
ppi_all['Real GDP'] = real_gdp['% Change Annualised']
ppi_all

            PPIACO  % Change  Real GDP
DATE
1913-01-01    12.1       NaN       NaN
1913-02-01    12.0 -0.008264       NaN
1913-03-01    12.0  0.000000       NaN
1913-04-01    12.0  0.000000       NaN
1913-05-01    11.9 -0.008333       NaN
...            ...       ...       ...
2020-02-01   196.7 -0.013046       NaN
2020-03-01   193.8 -0.014743       NaN
2020-04-01   186.0 -0.040248 -0.379789
2020-05-01   189.4  0.018280       NaN
2020-06-01   191.1  0.008976       NaN

[1290 rows x 3 columns]

In [15]:
# PPI x F&E
ppixfe = pdr.DataReader('WPSFD4131', data_source='fred', start='1974-01-01')
ppixfe['% Change'] = ppixfe['WPSFD4131'].pct_change()
ppixfe['Real GDP'] = real_gdp['% Change Annualised']
ppixfe

            WPSFD4131  % Change  Real GDP
DATE
1974-01-01       49.7       NaN -0.034391
1974-02-01       50.0  0.006036       NaN
1974-03-01       50.5  0.010000       NaN
1974-04-01       51.1  0.011881  0.009507
1974-05-01       52.2  0.021526       NaN
...               ...       ...       ...
2020-02-01      209.3  0.002875       NaN
2020-03-01      209.7  0.001911       NaN
2020-04-01      209.6 -0.000477 -0.379789
2020-05-01      209.8  0.000954       NaN
2020-06-01      209.9  0.000477       NaN

[558 rows x 3 columns]